// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALRLsEZcWAvclP7aK2FA1UgcbjdslsajI',
    appId: '1:193941780564:web:67df0f71914a6eea0195c1',
    messagingSenderId: '193941780564',
    projectId: 'newcommerce-df096',
    authDomain: 'newcommerce-df096.firebaseapp.com',
    storageBucket: 'newcommerce-df096.appspot.com',
    measurementId: 'G-2CTWP723FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7L6zWY93kNrbg8AEsXf6kwvDyD2onHBM',
    appId: '1:193941780564:android:b9c0f79d38dab5d20195c1',
    messagingSenderId: '193941780564',
    projectId: 'newcommerce-df096',
    storageBucket: 'newcommerce-df096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Cb-Ij8GEzhUCC_iMScMdm7upppEVu60',
    appId: '1:193941780564:ios:07ffe75621a203ea0195c1',
    messagingSenderId: '193941780564',
    projectId: 'newcommerce-df096',
    storageBucket: 'newcommerce-df096.appspot.com',
    iosBundleId: 'com.example.newcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Cb-Ij8GEzhUCC_iMScMdm7upppEVu60',
    appId: '1:193941780564:ios:3c8ac6dd3f66ebc10195c1',
    messagingSenderId: '193941780564',
    projectId: 'newcommerce-df096',
    storageBucket: 'newcommerce-df096.appspot.com',
    iosBundleId: 'com.example.newcommerce.RunnerTests',
  );
}
